FROM openjdk:21-jdk-slim as springboot
COPY ./target/postgrescoingecko-0.0.1-SNAPSHOT.jar /postgrescoingecko-0.0.1-SNAPSHOT.jar
EXPOSE 8080
CMD ["java", "-Xmx1024m", "-jar", "-Dspring-boot.run.profiles=docker", "/postgrescoingecko-0.0.1-SNAPSHOT.jar"]
